[colors.primary]
background = '#18120c'
foreground = '#eee0d4'

[colors.cursor]
text = '#eee0d4'
cursor = '#d4c4b5'

[colors.vi_mode_cursor]
text = '#18120c'
cursor = '#f7bb70'

[colors.search.matches]
foreground = '#504539'
background = '#bbcd9f'

[colors.search.focused_match]
foreground = '#504539'
background = '#f7bb70'

[colors.footer_bar]
foreground = '#504539'
background = '#eee0d4'

[colors.hints.start]
foreground = '#504539'
background = '#dfc2a2'

[colors.hints.end]
foreground = '#504539'
background = '#dfc2a2'

[colors.selection]
text = '#18120c'
background = '#f7bb70'


[colors.normal]
black = '#181818'
red = '#ffb4ab'
green = '#f7bb70'
yellow = '#825512'
blue = '#f7bb70'
magenta = '#bbcd9f'
cyan = '#dfc2a2'
white = '#BAC2DE'


[colors.bright]
black = '#585B70'
red = '#F38BA8'
green = '#A6E3A1'
yellow = '#F9E2AF'
blue = '#89B4FA'
magenta = '#F5C2E7'
cyan = '#94E2D5'
white = '#A6ADC8'


[colors.dim]
black = '#45475A'
red = '#F38BA8'
green = '#A6E3A1'
yellow = '#F9E2AF'
blue = '#89B4FA'
magenta = '#F5C2E7'
cyan = '#94E2D5'
white = '#BAC2DE'
